---
#This file prepared by Saleh Miri
####################################
# Section 1 Variables

# 1.1.1
# win22cis_passwordhistorysize is the number of past PW before they can be reused
# This value should be set to 24 or more to be CIS compliant
win22cis_passwordhistorysize: 24

# 1.1.2
# win22cis_maximumpasswordage is the maximum password age in days
# This value should be set to 365 or fewer, but not 0, to be CIS compliant
win22cis_maximumpasswordage: 365

# 1.1.3
# win22cis_minimumpasswordage is the minimum password age in days
# This value should be set to 1 or more days to be CIS compliant
win22cis_minimumpasswordage: 1

# 1.1.4
# win22cis_minimumpasswordlength is the minimum number of characters needed for a password
# This value should be set to 14 or more to be CIS compliant
win22cis_minimumpasswordlength: 14

# 1.2.1
# win22cis_lockoutduration is the duration a locked account stays locked in minutes
# This value should be set to 15 or more to be CIS compliant
win22cis_lockoutduration: "15"

# 1.2.2
# win22cis_lockoutbadcount is the number of failed login attempts before locking account
# This value should be set to 5 or fewer, but not 0, to be CIS compliant
win22cis_lockoutbadcount: 5

# 1.2.3
# win22cis_resetlockoutcount is the amount of time in minutes before a reset after an account lockout
# This value should be set to 15 or fewer to be CIS compliant
win22cis_resetlockoutcount: 15

####################################
# Section 2 Variables

# 2.2.18
# is_hyperv_installed is Hyper-V installed
win22cis_hyperv_installed: false

# 2.2.33
win22cis_increase_scheduling_priority_users: Administrators

# 2.3.1.5
# win22cis_admin_username is the name the administrator account will be renamed to
win22cis_admin_username: Administrator

# 2.3.1.6
# win22cis_guest_username is the name the guest account will be renamed to
win22cis_guest_username: guestchangethis

# 2.3.6.5
# win22cis_machine_acct_pw_age is the max machine account pw age in days
# This value should be set to 30 or fewer, but not zero, to be CIS compliant
win22cis_machine_acct_pw_age: 30

# 2.3.7.3
# win22cis_inactivity_timeout is the timeout in seconds for how long to wait for activity
# This value should be 900 or vewer, but not zero, to be CIS compliant
win22cis_inactivity_timeout: 900


# 2.3.7.4
win22cis_legalnoticetext: 'This system is for authorized use only. All access is monitored and recorded.'

# 2.3.7.5
win22cis_legalnoticecaption: 'WARNING'

# 2.3.7.6
# win22cis_cached_logons_count is the number of logons that are cached
# This needs to be 4 or fewer to be CIS compliant
win22cis_cached_logons_count: 4

# 2.3.7.7
# win22cis_passwd_expiry_warn is the number of days before an expring password users will receive warnings about the expring password
# This needs to be between 4 adn 14 days to be CIS compliant
win22cis_passwd_expiry_warn: 14

# 2.3.7.9
# win22cis_smartc_remove_option is the reg key option on the action when a SmartCard is removed
# This needs to be set to 1 (Lock Workstation) or 2 (Force Logoff) to be CIS compliant
win22cis_smartc_remove_option: "1"

# 2.3.9.1
# win22cis_auto_disconnect is the duration in minutes of idle time before suspending the session
# This needs to be set to 15 or fewer to be CIS compliant
win22cis_auto_disconnect: 15
####################################
# Section 9 Variables

# 9.1.5
# domain_firewall_log_path is the path to the domain firewall log files. The control suggests %SystemRoot%\System32\logfiles\firewall\domainfw.log
# This is a variable to give some leway on where to store these log files
win22cis_domain_firewall_log_path: '%SystemRoot%\System32\logfiles\firewall\domainfw.log'

# 9.1.6
# domain_firewall_log_size is the size of the log file generated
# To conform to CIS standards the value should be 16,384 or greater. Value is in KB
win22cis_domain_firewall_log_size: 16,384

# 9.2.5
# private_firewall_log_path is the path to the private firewall log files. The control suggests %SystemRoot%\System32\logfiles\firewall\privatefw.log
# This is a variable to give some leway on where to store these log files
win22cis_private_firewall_log_path: '%SystemRoot%\System32\logfiles\firewall\privatefw.log'

# 9.2.6
# private_firewall_log_size is the size of the log file
# To conform to CIS stadnards the value should be 16,384 or greater. Value is in KB
win22cis_private_firewall_log_size: 16,384

# 9.3.7
# public_firewall_log_path is the path to the public firewall log file. The control suggests %SystemRoot%\System32\logfiles\firewall\publicfw.log
# This is a variable to give some leway on where to store these log files
win22cis_public_firewall_log_path: '%SystemRoot%\System32\logfiles\firewall\publicfw.log'

# 9.3.8
# public_firewall_log_size is the size of the log file
# To conform to CIS stadnards the value should be 16,384 or greater. Value is in KB
win22cis_public_firewall_log_size: 16,384
####################################
# Section 18 Variables

# Control 18.2.5
# laps_passwordlength is the LAPS tool password length.
# To conform to CIS standards please use a min value of 15 and max value of 127
win22cis_laps_passwordlength: 15

# Control 18.2.6
# laps_passwordagedays is the LAPS tool password age in days
# To conform to CIS standards please use a max value of 30
win22cis_laps_passwordagedays: 30

# 18.3.6
# netbt_nodetype is the node type value in HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\NetBT\Parameters:NodeType
# Options are B-node value of 1, P-node value of 2, M-node value of 4, H-node value of 8. P-node is the recommended setting from CIS
win22cis_netbt_nodetype: 2

# 18.4.9
# win22cis_screen_saver_grace is the time in seconds before the screen saver grace period expires
# To conform to CIS standards the value should be 5 or fewer, with zero as recommended
win22cis_screen_saver_grace: 0

# 18.4.12
# win22cis_mss_security_warn_thresh is the threshold at which the event log will start warning
# To conform to CIS standards the value should be 90 or less
win22cis_mss_security_warn_thresh: 90

# 18.5.4.1
# win22cis_dns_over_https is the registry value for the DoHPolicy regkey entry
# To conform to CIS standards this value needs to be 0 or 1
win22cis_dns_over_https: 1

# 18.8.40.1
# win22cis_sam_ng_key_roc is the value for the ROCA-vulnerable WHfB keys during authentication registry key value
# To conform to CIS standards this value needs to be 1 or 2
win22cis_sam_ng_key_roc: 1

# 18.9.15.1
# wincis_require_pin_pairing is the value for the require pin for pairing registry key
# To conform to CIS standards this value should be 1 or 2
win22cis_require_pin_pairing: 1

# 18.9.17.1
# win22cis_diag_data is the value for the Allow Diagnostic Data registry key
# To confrom to CIS standards this value should be a 0 or 1
win22cis_diag_data: 0

# 18.9.27.1.2
# win22cis_elm_applog_max_size is the max size of the Event Log Manager Application logs can become, in KB
# To conform to CIS stadnards this value should be 32768 or greater
win22cis_elm_applog_max_size: 65538

# 18.9.27.2.2
# win22cis_elm_seclog_max_size is the max size of the Event Log Manager Security logs can become, in KB
# To confrom to CIS standards this value should be 196608 or greater
win22cis_elm_seclog_max_size: 196608

# 18.9.27.3.2
# win22cis_elm_setup_max_size is the max size of the Even Log Manager non- standard logs can become, in KB
# To conform to CIS standards this value should be 32768 or higher
win22cis_elm_setup_max_size: 32768

# 18.9.27.4.2
# win22cis_elm_syslog_max_size is the max size of the Event Long Manager System logs can become, in KB
# To conform to CIS standards this value should be 32768 or higher
win22cis_elm_syslog_max_size: 32768

# 18.9.65.3.10.1
# win22cis_terminal_max_idle_time is the time limit for active but idle remote desktop services connections in seconds
# This value needs to be 15 minutes (900000) or less, but not zero (0) to conform to CIS standards
win22cis_terminal_max_idle_time: 900000

# 18.9.89.2
# win22cis_allow_ink_workspace is the registry key value for the allowing windows ink workspace
# To conform to CIS stadnards this value should be a 0 or 1
win22cis_allow_ink_workspace: 1

# 19.9.108.4.2
# win22cis_defer_feature_update_period is the duration in days to delay feature updates in automatic updates
# To conform to CIS stadnards this value should be 180 or more (365 is max allowed by Windows)
win22cis_defer_feature_update_period: 180
####################################
# Section 19 Variables

# win22cis_screen_saver_timeout is the time in seconds until the screen saver turns on
# This needs to be set to 900 or fewer, but not zero, to be CIS compliant
win22cis_screen_saver_timeout: 900

