---
#Provided by Saleh Miri
#Section 05

- name: " 5.1 | PATCH | Ensure 'Print Spooler (Spooler)' is set to 'Disabled' (DC only) and 5.2 | PATCH | Ensure 'Print Spooler (Spooler)' is set to 'Disabled' ( MS only)"
  ansible.windows.win_regedit:
      path: HKLM:\System\CurrentControlSet\Services\Spooler
      name: Start
      data: 0
      type: dword
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_5.1
      - automated
      - printer

...
